#spring.application.name=journalApp
#spring.data.mongodb.uri=mongodb+srv://anubhavbiswas25:Anubhav0224@cluster0.hkpf4kd.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journalDB
#spring.data.mongodb.auto-index-creation=true
##automatically indexes the Users.username as they are unique
#spring.main.allow-circular-references=true
##so that circular-references aren't hindered in the springSecurity file of passwordEncoder()
#
##security logs
#logging.level.org.springframework.security=DEBUG
#
##this is just like .env files <K,V>